fos_rest:
    exception:
      codes:
          'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
          'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
    param_fetcher_listener: 'force'
    view:
        formats:
            json: true
        mime_types:
            json: ['application/json', 'application/x-json', 'application/vnd.example-com.foo+json']
            png: 'image/png'
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        view_response_listener: 'force'
#    format_listener:
#        default_priorities:
#            - json
    routing_loader:
        default_format: json

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }